/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./InfinityBuilder.types";
import * as _1 from "./InfinityBuilder.client";
import * as _2 from "./InfinityBuilder.message-composer";
import * as _3 from "./InfinityBuilder.react-query";
import * as _4 from "./InfinityFactory.types";
import * as _5 from "./InfinityFactory.client";
import * as _6 from "./InfinityFactory.message-composer";
import * as _7 from "./InfinityFactory.react-query";
import * as _8 from "./InfinityGlobal.types";
import * as _9 from "./InfinityGlobal.client";
import * as _10 from "./InfinityGlobal.message-composer";
import * as _11 from "./InfinityGlobal.react-query";
import * as _12 from "./InfinityIndex.types";
import * as _13 from "./InfinityIndex.client";
import * as _14 from "./InfinityIndex.message-composer";
import * as _15 from "./InfinityIndex.react-query";
import * as _16 from "./InfinityPair.types";
import * as _17 from "./InfinityPair.client";
import * as _18 from "./InfinityPair.message-composer";
import * as _19 from "./InfinityPair.react-query";
import * as _20 from "./InfinityRouter.types";
import * as _21 from "./InfinityRouter.client";
import * as _22 from "./InfinityRouter.message-composer";
import * as _23 from "./InfinityRouter.react-query";
export namespace contracts {
  export const InfinityBuilder = { ..._0,
    ..._1,
    ..._2,
    ..._3
  };
  export const InfinityFactory = { ..._4,
    ..._5,
    ..._6,
    ..._7
  };
  export const InfinityGlobal = { ..._8,
    ..._9,
    ..._10,
    ..._11
  };
  export const InfinityIndex = { ..._12,
    ..._13,
    ..._14,
    ..._15
  };
  export const InfinityPair = { ..._16,
    ..._17,
    ..._18,
    ..._19
  };
  export const InfinityRouter = { ..._20,
    ..._21,
    ..._22,
    ..._23
  };
}