/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions } from "react-query";
import { Decimal, Uint128, InstantiateMsg, CodeIds, Coin, ExecuteMsg, QueryMsg } from "./InfinityBuilder.types";
import { InfinityBuilderQueryClient } from "./InfinityBuilder.client";
export const infinityBuilderQueryKeys = {
  contract: ([{
    contract: "infinityBuilder"
  }] as const),
  address: (contractAddress: string | undefined) => ([{ ...infinityBuilderQueryKeys.contract[0],
    address: contractAddress
  }] as const)
};
export const infinityBuilderQueries = {};
export interface InfinityBuilderReactQuery<TResponse, TData = TResponse> {
  client: InfinityBuilderQueryClient | undefined;
  options?: UseQueryOptions<TResponse, Error, TData>;
}