/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Decimal, Uint128, InstantiateMsg, GlobalConfigForString, Coin, ExecuteMsg, QueryMsg, Addr, GlobalConfigForAddr, NullableCoin } from "./InfinityGlobal.types";