/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  infinity_global: string;
}
export type ExecuteMsg = {
  create_pair: {
    pair_config: PairConfigForString;
    pair_immutable: PairImmutableForString;
  };
} | {
  create_pair2: {
    pair_config: PairConfigForString;
    pair_immutable: PairImmutableForString;
  };
};
export type BondingCurve = "constant_product" | {
  linear: {
    delta: Uint128;
    spot_price: Uint128;
  };
} | {
  exponential: {
    delta: Decimal;
    spot_price: Uint128;
  };
};
export type Uint128 = string;
export type Decimal = string;
export type PairType = ("token" | "nft") | {
  trade: {
    reinvest_nfts: boolean;
    reinvest_tokens: boolean;
    swap_fee_percent: Decimal;
  };
};
export interface PairConfigForString {
  asset_recipient?: string | null;
  bonding_curve: BondingCurve;
  is_active: boolean;
  pair_type: PairType;
}
export interface PairImmutableForString {
  collection: string;
  denom: string;
  owner: string;
}
export type QueryMsg = {
  next_pair: {
    sender: string;
  };
};
export type Addr = string;
export type Binary = string;
export interface NextPairResponse {
  counter: number;
  pair: Addr;
  salt: Binary;
  sender: Addr;
}