/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  infinity_global: string;
}
export type ExecuteMsg = {
  swap_nfts_for_tokens: {
    collection: string;
    denom: string;
    filter_sources?: NftForTokensSource[] | null;
    sell_orders: SellOrder[];
    swap_params?: SwapParamsForString | null;
  };
} | {
  swap_tokens_for_nfts: {
    collection: string;
    denom: string;
    filter_sources?: TokensForNftSource[] | null;
    max_inputs: Uint128[];
    swap_params?: SwapParamsForString | null;
  };
};
export type NftForTokensSource = "infinity";
export type Uint128 = string;
export type TokensForNftSource = "infinity";
export interface SellOrder {
  input_token_id: string;
  min_output: Uint128;
}
export interface SwapParamsForString {
  asset_recipient?: string | null;
  robust?: boolean | null;
}
export type QueryMsg = {
  nfts_for_tokens: {
    collection: string;
    denom: string;
    filter_sources?: NftForTokensSource[] | null;
    limit: number;
  };
} | {
  tokens_for_nfts: {
    collection: string;
    denom: string;
    filter_sources?: TokensForNftSource[] | null;
    limit: number;
  };
} | {
  sim_sell_to_pair_quotes: {
    limit: number;
    pair: Pair;
  };
} | {
  sim_buy_from_pair_quotes: {
    limit: number;
    pair: Pair;
  };
};
export type Addr = string;
export type BondingCurve = "constant_product" | {
  linear: {
    delta: Uint128;
    spot_price: Uint128;
  };
} | {
  exponential: {
    delta: Decimal;
    spot_price: Uint128;
  };
};
export type Decimal = string;
export type PairType = ("token" | "nft") | {
  trade: {
    reinvest_nfts: boolean;
    reinvest_tokens: boolean;
    swap_fee_percent: Decimal;
  };
};
export interface Pair {
  config: PairConfigForAddr;
  immutable: PairImmutableForAddr;
  internal: PairInternal;
  total_tokens: Uint128;
}
export interface PairConfigForAddr {
  asset_recipient?: Addr | null;
  bonding_curve: BondingCurve;
  is_active: boolean;
  pair_type: PairType;
}
export interface PairImmutableForAddr {
  collection: Addr;
  denom: string;
  owner: Addr;
}
export interface PairInternal {
  buy_from_pair_quote_summary?: QuoteSummary | null;
  sell_to_pair_quote_summary?: QuoteSummary | null;
  total_nfts: number;
}
export interface QuoteSummary {
  fair_burn: TokenPayment;
  royalty?: TokenPayment | null;
  seller_amount: Uint128;
  swap?: TokenPayment | null;
}
export interface TokenPayment {
  amount: Uint128;
  recipient: Addr;
}
export type ArrayOfNftForTokensQuote = NftForTokensQuote[];
export interface NftForTokensQuote {
  address: Addr;
  amount: Uint128;
  source: NftForTokensSource;
}
export interface QuotesResponse {
  denom: string;
  quotes: Uint128[];
}
export type ArrayOfTokensForNftQuote = TokensForNftQuote[];
export interface TokensForNftQuote {
  address: Addr;
  amount: Uint128;
  source: TokensForNftSource;
}