/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Decimal = string;
export type Uint128 = string;
export interface InstantiateMsg {
  admin?: string | null;
  code_ids: CodeIds;
  default_royalty_fee_percent: Decimal;
  fair_burn: string;
  fair_burn_fee_percent: Decimal;
  marketplace: string;
  max_royalty_fee_percent: Decimal;
  max_swap_fee_percent: Decimal;
  min_prices: Coin[];
  pair_creation_fee: Coin;
  royalty_registry: string;
}
export interface CodeIds {
  infinity_factory: number;
  infinity_global: number;
  infinity_index: number;
  infinity_pair: number;
  infinity_router: number;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export interface ExecuteMsg {
  [k: string]: unknown;
}
export type QueryMsg = string;