/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  infinity_global: string;
}
export type ExecuteMsg = {
  update_pair_indices: {
    buy_from_pair_quote?: Uint128 | null;
    collection: string;
    denom: string;
    sell_to_pair_quote?: Uint128 | null;
  };
};
export type Uint128 = string;
export type QueryMsg = {
  sell_to_pair_quotes: {
    collection: string;
    denom: string;
    query_options?: QueryOptionsForPairQuoteOffset | null;
  };
} | {
  buy_from_pair_quotes: {
    collection: string;
    denom: string;
    query_options?: QueryOptionsForPairQuoteOffset | null;
  };
};
export type QueryBoundForPairQuoteOffset = {
  inclusive: PairQuoteOffset;
} | {
  exclusive: PairQuoteOffset;
};
export interface QueryOptionsForPairQuoteOffset {
  descending?: boolean | null;
  limit?: number | null;
  max?: QueryBoundForPairQuoteOffset | null;
  min?: QueryBoundForPairQuoteOffset | null;
}
export interface PairQuoteOffset {
  amount: number;
  pair: string;
}
export type Addr = string;
export type ArrayOfPairQuote = PairQuote[];
export interface PairQuote {
  address: Addr;
  collection: Addr;
  quote: Coin;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}