/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./InfinityPool.types";
import * as _1 from "./InfinityPool.client";
import * as _2 from "./InfinityPool.message-composer";
export namespace contracts {
  export const InfinityPool = { ..._0,
    ..._1,
    ..._2
  };
}