/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Addr, ConfigResponse, Config, InstantiateMsg, Uint128, NftSwap, BondingCurve, Decimal, PoolType, PoolInfo, PoolNftSwap, PoolQuoteResponse, PoolQuote, PoolsByIdResponse, Pool, PoolsResponse, QueryOptionsForTupleOfUint128AndUint64, QueryOptionsForUint64, Timestamp, Uint64, SwapParams, TransactionType, SwapResponse, Swap, TokenPayment, NftPayment } from "./InfinityPool.types";